services:
  php:
    build: .
    volumes:
      - .:/var/www/budgie
    networks:
      - budgie
    container_name: budgie-php

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/budgie
      - ./deploy/nginx.dev.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
    networks:
      - budgie
    container_name: budgie-nginx

  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - budgie
    container_name: budgie-mailhog

networks:
  budgie:
    driver: bridge
